import { FC } from "react";
import Head from 'next/head';
import MetaTag from "../MetaTag";
import { useRouter } from 'next/router'
import favicon from "../../public/img/sns_favicon.png"
interface IMetaData {
    meta_data?: any;
    url: string
}
const Header = ({ meta_data }: any) => {
    // const { url } = props
    console.log("Meta data icomingg", meta_data);
    const router = useRouter();
    console.log("in header")
    // console.log("Header url",url)
    // console.log("Header meta data",meta_data)
    let isDealer ;
    if (typeof window !== 'undefined') {
      isDealer = localStorage.getItem("isDealer");
    }
      console.log(isDealer);
      console.log(typeof isDealer);
    return (
        <Head>
            {/* <title>{meta_data?.length > 0 ? meta_data[0]?.meta_title : "Sport Network- Best in Cycling, E Bike, Motorsports,  equipments and gear"}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="keywords" content={meta_data?.length > 0 ? meta_data[0]?.meta_title : "Sport Network- Best in Cycling, E Bike, Motorsports,  equipments and gear"} />
            <meta name="description" content={meta_data?.length > 0 ? meta_data[0]?.description : "Sportnetwork have the greatest brands in bicycles, motorsports, and running items, equipment, and gear, with plans to expand our range to include more outdoor sports in the future."} />
            <meta name="robots" content={meta_data?.length > 0 ? meta_data[0]?.robot_name : "index"} />
            <meta property="og:image" content="https://admin.sportnetwork.in/uploads/application_images/original/gpMmVlq5wNkJ3UYK.png" />
            <meta property="og:title" content={meta_data?.length > 0 ? meta_data[0]?.meta_title : "Sport Network- Best in Cycling, E Bike, Motorsports,  equipments and gear"} />
            <meta property="og:description" content={meta_data?.length > 0 ? meta_data[0]?.description : "Sportnetwork have the greatest brands in bicycles, motorsports, and running items, equipment, and gear, with plans to expand our range to include more outdoor sports in the future."} />
            <meta property="og:type" content="website" />
            <meta property="og:url" content={`https://sportnetwork.in/${router?.pathname}`} />
            <link rel="canonical" href="$OG_URL" />
            <meta name="description" content="Generated by create next app" /> 
            <link rel="icon" href="/favicon.ico" />    */}
                 
        </Head>
    )
}



export default Header
